### ISSUE TITLE
How can I install an older version of this formula ?

### ISSUE THREAD

**Issue by marianobilli** [fluxcd/homebrew-tap#3]
I have an older flux version (0.26.1) which I cannot upgrade yet and I would like to install the flux cli for that version in my mac. 
The latest one fails as I have kubernetes cluster 1.21 and the kubectl version is incompatible.

Thanks.

**Comment by stefanprodan** [comment]
Until you can upgrade to latest, you can download any old binaries from the release page https://github.com/fluxcd/flux2/releases

**Comment by marianobilli** [comment]
Blazing fast response. Thanks!

**Comment by SebTardif** [comment]
Wow! I'm used to do brew update, and update everything and now VSCode and terminal doesn't work anymore with flux, and my installation is not even old. By default, this homebrew is expected to break with everybody existing installation. What about backward compatible for at least a few months...
