### ISSUE TITLE
Have native completion installation for bash, zsh and fish

### ISSUE THREAD

**Issue by remyleone** [fluxcd/homebrew-tap#7]
At the moment, when I'm installing flux with homebrew, I don't have completion available right out of the box. Could you make sure it is enabled for each shell (bash, fish, zsh and powershell)?

**Comment by stefanprodan** [comment]
Completions are enabled https://github.com/fluxcd/homebrew-tap/blob/master/Formula/flux.rb

**Comment by remyleone** [comment]
They are not working for me on bash and zsh natively. Strangely they are
working in fish 🤔

Le ven. 21 juil. 2023, 17:27, Stefan Prodan ***@***.***> a
écrit :
